# Generated by Django 5.0.3 on 2024-04-12 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userapikey",
            name="username",
            field=models.CharField(max_length=200),
        ),
    ]
