# Generated by Django 5.0.2 on 2024-03-05 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0003_task_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='base',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='head',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='pr_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
