# Generated by Django 5.0.2 on 2024-03-21 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0008_task_comment_url_task_response_comment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskevent',
            name='reversed',
            field=models.BooleanField(default=False),
        ),
    ]
