# Generated by Django 5.0.2 on 2024-03-21 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0009_taskevent_reversed'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='pilot_command',
            field=models.TextField(blank=True),
        ),
    ]
