# Generated by Django 5.0.2 on 2024-03-26 23:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0010_task_pilot_command'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskBill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('discount_percent', models.FloatField(default=0)),
                ('total_credits_used', models.FloatField(default=0)),
                ('user_is_owner', models.BooleanField(default=False)),
                ('project_is_open_source', models.BooleanField(default=False)),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='engine.task')),
            ],
        ),
    ]
