# Generated by Django 5.0.3 on 2024-05-17 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0013_alter_task_comment_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="gpt_model",
            field=models.CharField(
                blank=True, default="gpt-4-turbo", max_length=200, null=True
            ),
        ),
    ]
